### ISSUE TITLE
Module RCTNativeAppEventEmitter is not a registered callable module

### ISSUE THREAD

**Issue by cgilboy** [wmcmahan/React-Native-Calendar-Reminders#10]
Hello! 

I am also seeing the same exception as addressed in [PR 9](https://github.com/wmcmahan/React-Native-CalendarReminders/pull/9):
`Module RCTNativeAppEventEmitter is not a registered callable module.` in response to calling `RNCalendarReminders.saveReminder()` using RN 0.19. The PR fixes the issue for me. 

I was able to reproduce this in a new react-native 0.19 app that includes nothing but `react-native-calendar-reminders`. Let me know if I can provide any other info.

**Comment by wmcmahan** [comment]
Thanks the help @cgilboy. I'm able to reproduce this error in RN 0.19 if I don't include RN's NativeAppEventEmitter module:

```
var {NativeAppEventEmitter} = require('react-native');

// or

const {NativeAppEventEmitter} = React;
```

Does adding the NativeAppEventEmitter resolve the error?

**Comment by cgilboy** [comment]
Yep- Adding either of the above lines resolves the issue.

**Comment by wmcmahan** [comment]
Cool, I should probably add this to the readme.

**Comment by cgilboy** [comment]
Thanks!

**Comment by rajatj45** [comment]
Error: react native module rcteventemitter is not a registered callable module(calling receive touches)
 i have the above error could you please tell

var {NativeAppEventEmitter} = require('react-native');

where to add this line?
