### ISSUE TITLE
Errors when trying to fechAllReminders

### ISSUE THREAD

**Issue by geohuz** [wmcmahan/React-Native-Calendar-Reminders#12]
I am getting error 'undefined is not an object:

```
import RNCalendarReminders from 'react-native-calendar-reminders';
const {NativeAppEventEmitter} = React;
RNCalendarReminders.fetchAllReminders(reminders => {...})
```

I'm pretty new to react-native/ios programming, is any any example code to start with get authorized access to event store and fetch reminders?

follow up: I just figured out on 'add EventKit.framework to project libraries', but can't adding  the RNCalendarReminders into project libraries, and I'm not sure if I'm doing the right thing to fix the issue

follow up: I finally figured out how to adding the RNCalendarReminders into the project libraries. But still need full example guide on how to manipulate the event store.

**Comment by wmcmahan** [comment]
Thats a good idea, I will work on creating a simple example.

**Comment by geohuz** [comment]
Thanks a lot!
