### ISSUE TITLE
Support to check if an item has been 'marked done'

### ISSUE THREAD

**Issue by divyajalan** [wmcmahan/React-Native-Calendar-Reminders#13]
Hi,

As we know, on the native iOS **reminders** app we can **mark items done**, once the task has been completed. Is there any way in which we can read that value in react native through this component, so that we know whether the particular reminder/task was completed or not? 

I am sorry if this exists, I tried looking around but couldn't find this feature. Would be glad if this could be included!

**Comment by wmcmahan** [comment]
Hi @divyajalan. You are correct, being able to see completion state would be very helpful :)  It should be a simple feature addition to this module. I will try to push a change soon with this updated, or if you want, PRs are welcome also. Thanks for reaching out

**Comment by divyajalan** [comment]
Thanks a lot for the quick response @wmcmahan.
I will be eagerly waiting for this change to be pushed.

**Comment by wmcmahan** [comment]
No problem @divyajalan, I've pushed a new patch up that allows for checking if the reminder is completed along with the date it was marked completed. You can also now mark the reminder as completed on save, as well. The current property is named `isCompleted`. Hopefully this helps :)

**Comment by divyajalan** [comment]
I have checked this to work perfectly for me!
Thanks for being so quick at this @wmcmahan :)
