### ISSUE TITLE
Request for simpler function to update existing reminder

### ISSUE THREAD

**Issue by divyajalan** [wmcmahan/React-Native-Calendar-Reminders#14]
Hi @wmcmahan,

I was trying to update the reminder's isCompleted value from my application. Just to mark a reminder as completed, I don't want to use saveReminder and send all the details viz title, alarms, recurrence, notes, etc. Can we have an update method where if I say something like 

```
        RNCalendarReminders.updateReminder(reminder.id, {
            id: reminder.id,
            isCompleted: reminder.isCompleted,
        });

```

it should keep the remaining values as it is, rather than resetting everything?

**Comment by wmcmahan** [comment]
Hey @divyajalan, that's a good point. A more concise method to update reminder properties would definitely help. I will try to find some time soon to take a look at implementing that.

**Comment by wmcmahan** [comment]
Hi @divyajalan, i've added a method named `updateReminder` for simpler editing of an existing reminder. I hope it helps. Cheers!
