### ISSUE TITLE
Recurring reminder marked as done changes time of next notification.

### ISSUE THREAD

**Issue by superandrew213** [wmcmahan/React-Native-Calendar-Reminders#15]
To replicate:
1.  Add the following reminder:

```
        RNCalendarReminders.saveReminder('title', {
          notes: 'notes',
          startDate: '2016-10-01T09:45:00.000UTC',
          alarms: [{
            date: '2016-10-01T09:45:00.000UTC'
          }],
          recurrence: 'daily'
        });
```
1. Exit app and go to reminders. And mark it as done.
2. Refresh reminders by click show/hide completed if they don't update by themselves

When you click on info in reminders the alarm date is being changed and a due date has been added (which wasn't there when the reminder was added for the first time and is different from the alarm date).

**Comment by wmcmahan** [comment]
Thanks @superandrew213. Looks like it might be something with inaccurate timezone on date components. I'll try and get a fix out soon.

**Comment by superandrew213** [comment]
@wmcmahan awesome. Thank you!

**Comment by wmcmahan** [comment]
@superandrew213, I've pushed a patch to fix (hopefully) strange time shifting bug. Thanks for the help. Cheers!

**Comment by superandrew213** [comment]
thanks @wmcmahan but for some reason you can't add any recurring reminders anymore. Non recurring ones still work.

**Comment by wmcmahan** [comment]
Hmm, I also stopped setting `dueDate` on the native side, unless specified in the JS settings object. Maybe that is messing with the recurrence rules if not set.

```
RNCalendarReminders.saveReminder('title', {
   notes: 'notes',
   startDate: '2016-10-01T09:45:00.000UTC',
   dueDate: '2016-10-01T09:45:00.000UTC',
   alarms: [{
     date: '2016-10-01T09:45:00.000UTC'
   }],
   recurrence: 'daily'
 });
```

**Comment by superandrew213** [comment]
Yep, it's working with the due date. Could have sworn that I did test it with the due date too. Anyway all good. Thanks!

**Comment by superandrew213** [comment]
Will you set the due date on the native side again or will you make it required if recurrence is set?

**Comment by wmcmahan** [comment]
I could default the dueDate to be the same as the startDate on the native side, if a recurrence rule is set without a dueDate. Would that help, or just make things more confusing?

**Comment by superandrew213** [comment]
I think that might help since most of the time the dueDate will be the same as the startDate for recurring reminders. But that's up to you as long as it's in the docs it should be fine either way.
