### ISSUE TITLE
Fatal Error on saving reminder with custom id

### ISSUE THREAD

**Issue by rghorbani** [wmcmahan/React-Native-Calendar-Reminders#16]
I want to add custom id to reminder but I'm getting this error but it works fine without setting id.

[fatal][tid:com.facebook.react.RNCalendarRemindersQueue] Exception '**\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]' was thrown while invoking saveReminder on target RNCalendarReminders with params (
    "\U062a\U0648\U062c\U0647",
        {
        alarms =         (
                        {
                date = "2016-05-24T15:15:00.000Z";
            }
        );
        id = 1c1b4ab9df774316a84ca989070d5ce8;
        notes = Transaction;
        startDate = "2016-05-24T15:15:00.000Z";
    }
)

**Comment by wmcmahan** [comment]
You cannot explicitly add a custom ID when creating a new reminder. The EventStore will set a unique identifier after the reminder has been created. You should be able to retrieve this ID from the `saveReminder` callback.

**Comment by rghorbani** [comment]
but `saveReminder` don't have any callback???

**Comment by wmcmahan** [comment]
Sorry, I meant by listening for the event `remindersChanged` or `reminderSaveSuccess`.
