### ISSUE TITLE
Module breaking android release build

### ISSUE THREAD

**Issue by RemeJuan** [wmcmahan/React-Native-Calendar-Reminders#21]
I cannot even imagine where to begin debugging this, but for some unknown reason, and it quite frankly may actually have nothing to do with your module itself, but with this module installed, the android release build crashes, instantly on startup, like 5 screens away from where the module is even being used within the application.

Dev mode is fine, zero errors are raised anywhere for anything. I would expect that when building the android build steps would ignore everything to do with this, and as the module requiring this is only used when the device is IOS it should not even be looking for it even when it is on the relevant screen.

Any suggestions perhaps, I am hoping to avoid having to maintain 2 separate projects because of a button.

**Comment by wmcmahan** [comment]
Without knowing how your application is using this module, it will difficult to know what is causing an Android build to crash. It sounds like you may need to separate out the platform specific code.

**Comment by RemeJuan** [comment]
Yep, the implementation is extremely simple.

The app lists events in categories, and on the details page for each event is a OS specific set of buttons for adding the event to your calendar. So the only references to your module within the application are in the ButtonsCalendarIOS component, which depending on flow is 2 or 5 screens forward of the initial loading screen.

The index.ios.js does initial data checks before handing over to the main view which in turn renders the 'home' screen, but the crash is happening on initial application launch, from what I can see, even before the data check is initiated as that displays a loading screen.

Still some time before I get the ios dev account, maybe dumb luck will be in my favour on this one.

Thanks

**Comment by wmcmahan** [comment]
This issue should be resolved now.
