### ISSUE TITLE
Module does not work in release build.

### ISSUE THREAD

**Issue by harshvb7** [wmcmahan/React-Native-Calendar-Reminders#22]
# Nothing happens after saving the reminder.

It works on debug mode on simulator and even on device connected to the laptop but not on release.

Here's the code.

```
export const addScheduleItem = (data) => {
  return function(dispatch){
    dispatch({type: 'SCHEDULE_PROCESSING'});

    reminderData = {
      location: data.location,
      notes: data.notes,
      startDate: data.startDate,
      dueDate: data.startDate,
      alarms: [{
        date: data.startDate,
      }],
      recurrence: data.recurrence
    }
    RNCalendarReminders.saveReminder(data.title, reminderData);
    dispatch({type: 'SCHEDULE_ADDED', payload: reminderData});
  }
}

```

**Comment by wmcmahan** [comment]
Hi @harshvb7, what is the expected result after saving? Or is it not saving the reminder? Also, be aware that saving a reminder is async, so using calling dispatch after saveReminder like this is not guaranteed to work. This library uses [events](https://github.com/wmcmahan/React-Native-Calendar-Reminders#events) for callbacks, but I plan to update it with promises soon.

**Comment by harshvb7** [comment]
The 'dispatch' is only to trigger the add reminder form page to pop out and go back to the list.

After saving on debug:
Because of the remindersChanged listener added, the list gets a new item added.

After saving on Release:
Nothing happens. The reminder is not created. But if I go in the iOS Reminders app and create a new reminder manually and come back to the app, it adds shows new reminder in the list. 
Everything works on the release module, including editing , deleting, etc. It just doesn't work for saving. 

Is there anything to set in Xcode. My app deployment target is iOS 8.0. 

Thanks

**Comment by wmcmahan** [comment]
I'm not sure what is causing the release version to not save these reminders. If reading the reminders from the store works, it doesn't sound like a permissions problem. You could try to optimize the debug build similar to the release build, and check if any errors surface.

**Comment by harshvb7** [comment]
Ok,
I ran the release version on the device by editing the scheme from debug -> release. 
Now while saving, if recurrence is passed the reminder is saved with 'Invalid Date'.
Without recurrence the app just crashes.

Another weird thing is that. 
On debug: 
Saving works if remote JS debugging is ON
else it gives this error:
JSON value '2016-10-07' 7:30:25 pm +0000' of type NSDate cannot be converted to a date

**Comment by wmcmahan** [comment]
Looks like React Native might be having a hard time converting your start and due dates to an NSDate. Try using a Date instance as the value for the date properties.

**Comment by wmcmahan** [comment]
Ok, my fault. Looks like there was a bug around the authorization. Should be fixed now if you want to give it another try.

**Comment by harshvb7** [comment]
I fixed it by using date string instead of date object.
I was passing the javascript date object. I changed it to string of format '2016-10-01T09:45:00.000UTC' using moment js and it worked.
