### ISSUE TITLE
Can't create customized recurrence reminders

### ISSUE THREAD

**Issue by henryw4k** [wmcmahan/React-Native-Calendar-Reminders#23]
| Property | Value | Description |
| :-- | :-- | :-- |
| recurrence | String | The simple recurrence frequency of the reminder ['daily', 'weekly', 'monthly', 'yearly']. |

We have an app that requires 3 month, 6 month, 9 month recurrences. The current setup doesn't allow for that. Was wondering if this feature will come someday.

**Comment by henryw4k** [comment]
For reference, here's the PR that added simple recurrence rules to this library: https://github.com/wmcmahan/React-Native-Calendar-Reminders/pull/8/files#diff-2db8f8e7b39a1a189a5e8199f34ee1d8R260

**Comment by henryw4k** [comment]
It looks like we just need to pass an `interval` value (`3`, `6`, or `9`) to the recurrence rule, described here: https://developer.apple.com/reference/eventkit/ekrecurrencerule/1507273-init

**Comment by henryw4k** [comment]
started working on this feature in a forked version, but not sure know how to build it to test. 

https://github.com/doctordick/React-Native-Calendar-Reminders/commit/7e6c8a3c79bee22d3603d0bc136e573d59fc2486

**Comment by dsernst** [comment]
I helped @henryw4k write this extension to the library. It's now working as of https://github.com/doctordick/React-Native-Calendar-Reminders/commit/35f43899fd30f960045ab916ddcd1edcd28e4725

Still todo:
- [x] Document the new `recurrenceInterval` parameter
- [ ] Default to `recurrenceInterval = 1`, if it's not passed in.
