### ISSUE TITLE
Error installing library

### ISSUE THREAD

**Issue by lyahdav** [wmcmahan/React-Native-Calendar-Reminders#26]
A few issues I had during installation:

1. I think the README is missing a note about running `react-native link`.
1. After running that command, I had an error when compiling in Xcode where it was trying to build the `RNCalendarReminders` project but it failed because that project couldn't find React Native header files. I gave up on that approach and just manually added RNCalendarReminders.h and RNCalendarReminders.m to my Xcode project.
1. Then I got an error along the lines of "RCTBridgeModule.h not found" in `RNCalendarReminders.h`. The fix was to change `#import "RCTBridgeModule.h"` to `#import <React/RCTBridgeModule.h>`. It's possible because of the version of React Native I'm using. I'm on 0.41.2 via [Exponent](https://getexponent.com/)
1. Similar to the previous error, I got "RCTConvert.h not found" in `RNCalendarReminders.m`. I fixed by changing `#import "RCTConvert.h"` to `#import <React/RCTConvert.h>`.

**Comment by wmcmahan** [comment]
Thanks, @lyahdav. I've update this package for React Native v0.4x and added a note about linking to the README. These issues during installation should be resolved now. Cheers.
