### ISSUE TITLE
Lots of warnings in iOS 10 Xcode project when building

### ISSUE THREAD

**Issue by lyahdav** [wmcmahan/React-Native-Calendar-Reminders#27]
There are many warnings in `RNCalendarReminders.m` when compiling in Xcode in an iOS 10 project, mainly around deprecations:
![image](https://cloud.githubusercontent.com/assets/359157/24083434/efa50348-0c93-11e7-8237-085dccf9d3ec.png)

**Comment by wmcmahan** [comment]
Thanks @lyahdav, I've cleaned up these warning in the latest release.
