### ISSUE TITLE
Support for alerts?

### ISSUE THREAD

**Issue by ivanbrens** [wmcmahan/React-Native-Calendar-Reminders#4]
I really like this component, thanks for creating it.  I would really like to implement a reminder with an **alert** 30 minutes prior.  Can you support this?

Thanks

**Comment by wmcmahan** [comment]
Yes, I believe that would be a useful addition to the module. I will try and push some time aside to allow for attaching relative and absolute alarms. Thanks for the idea!

**Comment by ivanbrens** [comment]
Awesome! I look forward to it.  

I looked into it a little but and found a [link](http://stackoverflow.com/questions/8270117/how-to-set-a-reminderalarm-using-eventkit-framework-for-a-particular-date) that talks about it. I think it will come in handy.  I don't know very much objective-c, but I'll see what I can dig up.

**Comment by wmcmahan** [comment]
The ability to attach alarms to reminders has been added. This includes the ability to add alarms based on relative or absolute dates, as well as structured locations for geofencing. Hopefully this helps a little.
